[workspace]
resolver = "2"
members = ["crates/timegrapher-core", "crates/timegrapher-cli"]

[workspace.package]
version = "0.1.0"
edition = "2021"
license = "GPL-3.0-or-later"
repository = "https://github.com/peterhudson/timegrapher"
rust-version = "1.80"

[workspace.dependencies]
timegrapher-core = { path = "crates/timegrapher-core" }

[profile.release]
debug = 1
